# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6490c879339bec4fcf421185e16f92a3"
name = "Production Design Card – GF"
application_url = "https://all-quality-design-tool.vercel.app"
embedded = true

[access_scopes]
scopes = "read_orders"

[auth]
redirect_urls = [
  "https://all-quality-design-tool.vercel.app/api/auth",
]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = false
